import Head from "next/head";
import { Fragment } from "react";
import Hero from "../Components/Home/Hero";
import Works from "../Components/Home/Works";
import Layout from "../Components/Layout";
import Speciality from "../Components/Home/Speciality"
import Popular from "../Components/Home/Popular"
import Gallery from "../Components/Home/Gallery"
import Reviews from "../Components/Home/Reviews";
export default function Home() {
  return (
    <Fragment>
      <Layout>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
            integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
            crossOrigin="anonymous"
            referrerpolicy="no-referrer"
          />
        </Head>
        {/* body */}
        <main>
          {<Hero />}
          {
            <Speciality/>
          }
           {
            <Popular/>
          } 
          {
            <Works />
          }       
            {
              <Gallery/>
            }   
          
            {
              // <Reviews/>
            }   
          
           </main>
      </Layout>
    </Fragment>
  );
}
